#!/bin/bash
echo -e "Конвертер изображений на основе mogrify"
echo -e ""
echo -e "При помощи этого скрипта возможно конвертировать изображения в различные форматы с уточнением размера"
echo -e ""
echo -e "Автор: Платонов Марк"

while [ 1 ]
do
val=1
while [ $val -gt 0 ]
do
	echo "Введите имя файла: "
	read name
	if [ -e $name ]
	then
		val=0
	else
		echo "Файла не существует, попробовать еще раз? y/n"
		read ans
		if [ $ans != "y" ]
		then
			exit
		fi
	fi
done
val=1
while [ $val -gt 0 ]
do
	> errors
	echo "Введите необходимый формат: "
	read format
	mogrify -format $format 2> errors
	if [ -s errors ] #проверка на пустоту файла error
	then
		echo "Ошибка в выборе формата! Попробовать еще раз? y/n"
		read ans
		if [ $ans != "y" ]
		then
			exit
		fi
	else
		val=0
	fi
done
val=1
while [ $val -gt 0 ]
do
	> errors
	echo "Введите размер изображения (в формате N, NxN или N%)"
	read size
	mogrify -resize $size 2> errors
	if [ -s errors ] #проверка на пустоту файла error
	then
		echo "Ошибка! Неверно указан размер. Попробовать еще раз? y/n"
		read ans
		if [ $ans != "y" ]
		then
			exit
		fi
	else
		val=0
	fi
done
> errors
mogrify -resize $size -format $format $name 2> errors
if [ -s errors ]
then
	echo -e "Ошибка при выполнении mogrify"
	echo "Попробовать еще раз? y/n"
	read ans
	if [ $ans != "y" ]
	then
		exit 250
	fi
else
	echo -e "Успешно!"
	echo "Повторить? y/n"
	read ans
	if [ $ans != "y" ]
	then
		exit
	fi
fi
done
